### PR TITLE
Sign up page

### PR DESCRIPTION
**Pull request by LOctavio**
This a page that is a clone of the sign-up page of mint.com

In this  page we added:

-A sign in section
-A form with some fields to fill with own information to create a new account
-A content with legal information

This page only seems similar to the sign-up page of mint.com, so it doesn't have any function.

### CODE REVIEW

**Comment by majovanilla** [comment]
# Code Review in progress 👀 by Maria Reyes

**Comment by majovanilla** [comment]
Hey Team, 👋

## Good job on this project! 👍
The page looks very good!

There are still some changes 👇 you need to implement to approve this request 🔍

### Required Changes: ✍️

**General changes **

- Always remember to check your HTML using the [validator](https://validator.w3.org/). You have some errors and warnings. Please fix them.
Screenshot from 2020-02-24 17-19-17

- Always remember to check your linters!! You have a lot of errors that need to be corrected.

- Work on your Readme file. It should be descriptive of the project. You are using the right template but it's empty! Try to fill most of the subtitles, and if you don't need them, erase them. 
Screenshot from 2020-02-24 17-22-34
Screenshot from 2020-02-24 17-22-43

-Please write meaningful pull request messages. Check this [example](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/)

**Project specifics**

- You should use a form tag to enclose all the inputs. This is a Microverse requirement. See screenshot [here](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/html_forms/form_and_input_requirement.png)

- You should use specific **input types** for each field (tel, email, password) and the proper **labels**. This is a Microverse requirement. See screenshot [here](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/html_forms/form_and_input_requirement.png)

- Work on your reCaptcha div, so that it moves to the bottom of the form div so you don't have the white space. See screenshot:
Screenshot from 2020-02-24 17-38-16

- Work on the font size to make your elements look closer to the original page. Especially the footer.
-Use the same hover effect on the links of the footer.



### Optional Changes:

If you want to make your project even better 🔥💥, I have a few suggestions you can implement.  

These are completely [Optional]: 🦔

- You could use display flex on your #productIcons div to keep them vertically aligned, and then play with the margin between them to separate them a little.


**Please, make all REQUIRED changes and submit your request again! 😀**

## Status: Changes Required :warning: 


If you have any questions, feel free to send me a message through Slack (@majo)
I would be happy to help! 👩‍💻 


Happy coding 🤓

--Maria Reyes



You can find me on Social Media below 👇 . Remember to say hi!

[GitHub](https://github.com/majovanilla) [Twitter](https://twitter.com/MajoVanilla) [LinkedIn](https://www.linkedin.com/in/majoreyesparroquin/)

**Review by nikasulo — CHANGES_REQUESTED** [review]
# Under Review By Tolulope Olusakin(TSE)
Please check on this in a few minutes for some feedback! :+1:

**Review by nikasulo — CHANGES_REQUESTED** [review]
# Great job @LOctavio and @ishanchawla1! :clap: 
You did nicely incorporating some of the changes requested by @majovanilla, your PR is descriptive, your Readme is great and you used the validator well, however, there are still a few things outstanding such as:

* Her comments about the form
* Her comments about the Captcha section

Please look into these thoroughly, make the changes and reques another review! :+1: I wish you the best and see you at the top :rocket: 

##### Think I missed something? Need some help with this or any of your projects? Please feel free to reach out to me on [Twitter](https://twitter.com/oluwadamilareo_) or [Instagram](https://instagram.com/oluwadamilare_olusakin), even if you just want to chat and I will respond to you as soon as I can.

**Review by nikasulo — CHANGES_REQUESTED** [review]
# Great job @LOctavio and @ishanchawla1! :clap: 
You did nicely incorporating some of the changes requested by @majovanilla, your PR is descriptive, your Readme is great and you used the validator well, however, there are still a few things outstanding such as:

* Her comments about the form
* Her comments about the Captcha section

Please look into these thoroughly, make the changes and reques another review! :+1: I wish you the best and see you at the top :rocket: 

##### Think I missed something? Need some help with this or any of your projects? Please feel free to reach out to me on [Twitter](https://twitter.com/oluwadamilareo_) or [Instagram](https://instagram.com/oluwadamilare_olusakin), even if you just want to chat and I will respond to you as soon as I can.

**Review by mosesogwo — CHANGES_REQUESTED** [review]
**Hi @LOctavio, @ishanchawla1. You have done well with the recommended changes:+1:. But you have missed one of them**

- The type attribute for telephone field should be **tel** not **number**.

- Also, it seems stickler is not enabled for this repository. No linter tests were run. Kindly enable stickler and fix any errors that may arise. 

_**Make the changes and submit another code review request.**_

**Any question? You can reach me on Slack (Moses Ogwo)**

**Cheers:stars:**

**Review by nikasulo — APPROVED** [review]
# Wonderful work @LOctavio and @ishanchawla1
You may merge and keep going :clap: I wish you all the best on your journey! See you at the top :100: :medal_military: 

##### Think I missed something? Need some help with this or any of your projects? Please feel free to reach out to me on [Twitter](https://twitter.com/oluwadamilareo_) or [Instagram](https://instagram.com/oluwadamilare_olusakin), even if you just want to chat and I will respond to you as soon as I can.

**Pull request merged**
